language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw

notifications:
  email:
    recipients:
      -khalilikafo@gmail.com
      -omarkof99@gmail.com
    on_success: always # send email on success
    on_failure: always # send email on failure